package internal

const (
	NAME_MAX_LENGTH = 128
	NAME_MIN_LENGTH = 1
	BIO_MAX_LENGTH  = 512
	BIO_MIN_LENGTH  = 0

	USERNAME_MAX_LENGTH = 48
	USERNAME_MIN_LENGTH = 1
	PASSWORD_MAX_LENGTH = 255
	PASSWORD_MIN_LENGTH = 1
)
