services:
  meilisearch-service:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    networks:
      - creation-net
    environment:
      - MEILI_MASTER_KEY=yuxyuxx  # 设置 Meilisearch API 密钥（可选）
      - MEILI_ENV=development  # 运行环境，默认是 "production"
      - MEILI_NO_ANALYTICS=true  # 关闭匿名统计数据收集

networks:
  creation-net:
    external: true